const GET_COLOR = 'GET_COLOR';
const GET_COLOR_FROM_RGB = 'GET_COLOR_FROM_RGB';
const GET_COLOR_FROM_HEX = 'GET_COLOR_FROM_HEX';
const ActionTypes = {GET_COLOR,GET_COLOR_FROM_RGB, GET_COLOR_FROM_HEX};
